name: Wisecow CI/CD Local

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t wisecow:v1 .

      - name: Load image into Minikube
        run: |
          minikube image load wisecow:v1

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8s/namespace.yaml
          kubectl apply -f k8s/deployment.yaml -n wisecow
          kubectl apply -f k8s/services.yaml -n wisecow
          kubectl apply -f k8s/ingress.yaml -n wisecow